### ISSUE TITLE
angr | Lantern's 小站

### ISSUE THREAD

**Issue by Lantern-r** [Lantern-r/Lantern-r.github.io#97]
https://lantern.cool/note-tool-ida-python/ 

 angr 学习

**Comment by leilecen** [comment]
为什么我复制你的那道signal 的代码报错?
Traceback (most recent call last):
  File "e:\reverseBox\buuctf\singal\demo.py", line 11, in <module>
    sm.explore(find=is_good, avoid=is_bad)
  File "C:\Users\大白菜\.conda\envs\angr\Lib\site-packages\angr\sim_manager.py", line 332, in explore
    self.run(stash=stash, n=n, **kwargs)
  File "C:\Users\大白菜\.conda\envs\angr\Lib\site-packages\angr\sim_manager.py", line 362, in run
    self.step(stash=stash, **kwargs)
  File "C:\Users\大白菜\.conda\envs\angr\Lib\site-packages\angr\misc\hookset.py", line 96, in __call__
    result = current_hook(self.func.__self__, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\大白菜\.conda\envs\angr\Lib\site-packages\angr\exploration_techniques\explorer.py", line 108, in step
    return simgr.step(stash=stash, extra_stop_points=base_extra_stop_points | self._extra_stop_points, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\大白菜\.conda\envs\angr\Lib\site-packages\angr\misc\hookset.py", line 96, in __call__
    result = current_hook(self.func.__self__, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\大白菜\.conda\envs\angr\Lib\site-packages\angr\exploration_techniques\suggestions.py", line 43, in step
    simgr.step(stash=stash, **kwargs)
  File "C:\Users\大白菜\.conda\envs\angr\Lib\site-packages\angr\misc\hookset.py", line 101, in __call__
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\大白菜\.conda\envs\angr\Lib\site-packages\angr\sim_manager.py", line 471, in step
    successors = self.step_state(state, successor_func=successor_func, error_list=error_list, **run_args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\大白菜\.conda\envs\angr\Lib\site-packages\angr\sim_manager.py", line 512, in step_state
    successors = self.successors(state, successor_func=successor_func, **run_args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\大白菜\.conda\envs\angr\Lib\site-packages\angr\sim_manager.py", line 562, in successors
    return self._project.factory.successors(state, **run_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\大白菜\.conda\envs\angr\Lib\site-packages\angr\factory.py", line 82, in successors
    return self.default_engine.process(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\大白菜\.conda\envs\angr\Lib\site-packages\angr\engines\vex\light\slicing.py", line 20, in process
    return super().process(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\大白菜\.conda\envs\angr\Lib\site-packages\angr\engines\engine.py", line 162, in process
    self.process_successors(self.successors, **kwargs)
  File "C:\Users\大白菜\.conda\envs\angr\Lib\site-packages\angr\engines\failure.py", line 24, in process_successors
    return super().process_successors(successors, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\大白菜\.conda\envs\angr\Lib\site-packages\angr\engines\syscall.py", line 26, in process_successors
    return super().process_successors(successors, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\大白菜\.conda\envs\angr\Lib\site-packages\angr\engines\hook.py", line 67, in process_successors
    return self.process_procedure(state, successors, procedure, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\大白菜\.conda\envs\angr\Lib\site-packages\angr\engines\procedure.py", line 39, in process_procedure
    inst = procedure.execute(state, successors, ret_to=ret_to, arguments=arguments)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\大白菜\.conda\envs\angr\Lib\site-packages\angr\sim_procedure.py", line 278, in execute
    r = getattr(inst, inst.run_func)(*sim_args, **inst.kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\大白菜\.conda\envs\angr\Lib\site-packages\angr\procedures\win32\sim_time.py", line 127, in run
    val = claripy.BVS("GetTickCount_result", 32, key=("api", "GetTickCount"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\大白菜\.conda\envs\angr\Lib\site-packages\claripy\ast\bv.py", line 256, in BVS
    return BV(
           ^^^
TypeError: Base.__new__() got an unexpected keyword argument 'key'
